### PR TITLE
sqlalchemy 1.4 & 2.0 support (1.3 dropped)

### PR DESCRIPTION
**Pull request by jdimmerman**
Fixes for
* engine.execute is now connection.execute
* nested transaction management is different

Still one failing test

### CODE REVIEW

**Comment by olirice** [comment]
CI is passing. which test is failing for you locally?

The pre-commit CI check can be resolved with

```shell
pip install pre-commit
pre-commit install
pre-commit run --all
```
which will format the files

**Comment by jdimmerman** [comment]
Great thanks @olirice. I pushed the formatting fixes.

I'm seeing a failure for the following
```
src/test/test_recreate_dropped.py::test_succeeds_when_defering - sqlalchemy.exc.ProgrammingError: (psycopg2.errors.DuplicateTable) relation "branch" already exists
```

**Comment by jdimmerman** [comment]
Ah @olirice the test only fails with sqlalchemy 2+. I think ideally CI would run against 1.x and 2.x as part of this PR.

**Review by olirice — APPROVED** [review]

**Comment by olirice** [comment]
thanks for your work on this, I appreciate it!

the update is available on pypi `alembic_utils==0.8.1`

**Pull request merged**
