### PR TITLE
add support for composite types

### PR DESCRIPTION
**Pull request by timwoocker**
Support for migrating composite types in the format of:

"CREATE TYPE ... AS (...)"

I haven't found the time to add tests yet, would be nice if someone could add those.

### CODE REVIEW

**Comment by Chrisslue** [comment]
Well actually you cant "CREATE OR REPLACE" a Type. You have to remove it and create it again.

**Comment by timwoocker** [comment]
> Well actually you cant "CREATE OR REPLACE" a Type. You have to remove it and create it again. Or alter it

You are right. `CREATE OR REPLACE` doesn't exist for types. But removing and re-adding it is not an option here because the whole point of migrations is that you don't lose your references. You'd need to set `CASCADE` and that would delete all functions and tables referencing your type.
Instead we need to run `ALTER TYPE` to update the type accordingly (drop, change or add attributes themselves).

My next commit will propose a possible solution.

**Comment by timwoocker** [comment]
My implementation only checks if the regtype of the type in the db and the defined one are the same, not the regmod. That is because the system function in postgres needed for checking this is only added in version 17: https://www.postgresql.org/docs/17/functions-info.html (`to_regtypemod`)

How does this project handle compatibility? Should the code be compatible with <17 and >17 (with a different implementation) or only >17 or is it fine if it's not "perfect" but compatible with all versions (the way I implemented it right here)?


I also noticed that the definition retrieved from the database might rename types using their alias. For example if you define an attribute using type `VARCHAR`, the retrieved type from the db is `character varying` making the definition different. Does anyone have any suggestion on how we could fix this? Right now I just ignore that fact so if you create a type that uses a type "VARCHAR", it will always detect the attribute as having a changed type.

**Comment by olirice** [comment]
thanks for opening this but we're unlikely to support any new entities that do not support `create or replace` directly

I'd recommend using `op.execute("...")` for managing your composite types

**Pull request closed without merging**
