### PR TITLE
Quote trigger signatures during creation

### LINKED ISSUE #74: Better handling of quoted entities
Firstly, thanks for this amazing library. While integrating with our system we've hit a bit of a snag with the way quoted entities are handled.

In our case we have triggers that need to be quoted in order to match (not created by us, created by [Hasura](https://github.com/hasura/graphql-engine), so I'd rather handle them, if possible).

As you know, `ReplaceableEntity` switches the signatures to unquoted on the way in for both the entities and the objects reflected from the db. That means that when it comes to the drop stage in `get_database_definition`, the existing triggers _aren't_ dropped and hence the entities are seen as new. The end result is that we end up with CreateOps for any quoted entities and DropOps for their corresponding db objects every time.

As a workaround, I'm thinking to subclass PGTrigger so that I can handle the quoted case a bit better, but I'd like to get your opinion on it in case you'd like me to submit a PR back to handle it generally (and if so, I'd rather approach it in your preferred way from the outset).

It _seems_ like it would be ok to simply not coerce to the unquoted version in the constructor (of `ReplaceableEntity`, ideally) and then change `to_variable_name` to switch to unquoted first.

I'll try that locally and await your thoughts before submitting a PR.

Thanks again.

### PR DESCRIPTION
**Pull request by olirice**
Resolves #74

### CODE REVIEW

**Comment by olirice** [comment]
@aidos when you get the chance, could you please try this branch and see if it resolves the issue you're seeing in #74?

**Comment by aidos** [comment]
Sure thing.

**Comment by aidos** [comment]
Sorry, saw this on email and thought you were asking me to create a PR so I started down that path.

This branch is working for me now.

**Comment by olirice** [comment]
great, the fix is available in `alembic_utils>=0.7.6` on pypi

**Comment by aidos** [comment]
Installed from pip and it works perfectly. Do you think it's worth doing the rest of the objects using the same approach? I'm happy to make a PR (I ran into an issue earlier running the tests - something to do with docker, but not sure what yet).

**Comment by olirice** [comment]
> Do you think it's worth doing the rest of the objects using the same approach

Yes, but its already in place for `PGView`, `PGMaterizedView` and `PGFunction` although its handled a little differently in those cases

If you see an error somewhere lmk

>  issue earlier running the tests

if you send me the error message I'm happy to take a look

**Pull request merged**
